PhotoSchool2/PhotoSchool2/Models/Homework.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PhotoSchool2.Models
{
    public class Homework
    {
        [Key]
        public int Id { get; set; }
        public string Title { get; set; }
        public int NumberOfPhotos { get; set; }
        public string Text { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime Date { get; set; }

        public virtual ICollection<HomeworkPhoto> Photos { get; set; }
    }
}

PhotoSchool2/PhotoSchool2/Controllers/HomeworkController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PhotoSchool2.Models;

namespace PhotoSchool2.Controllers
{
    public class HomeworkController : Controller
    {
        IRepository<Homework> db;
        public HomeworkController()
        {
            db = new HomeworkRepository();
        }


        // GET: Homework
        public ActionResult Index()
        {
            if (User.IsInRole("admin")) return View("IndexAdmin", db.GetList());
            else if (User.IsInRole("user")) return View("IndexUser", db.GetList());
            else return View("Index", db.GetList());
        }

        // GET: Homework/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Homework homework = db.Get(id);
            if (homework == null)
            {
                return HttpNotFound();
            }
            return View(homework);
        }

        // GET: Homework/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Homework/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,NumberOfPhotos,Text")] Homework homework, HttpPostedFileBase[] fileUpload)
        {
            if (ModelState.IsValid)
            {
                db.Create(homework, fileUpload);
                db.Save();
                return RedirectToAction("Index");
            }

            return View(homework);
        }

        // GET: Homework/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Homework homework = db.Get(id);
            if (homework == null)
            {
                return HttpNotFound();
            }
            return View(homework);
        }

        // POST: Homework/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,NumberOfPhotos,Text,Date")] Homework homework, string[] DeleteCheckBox, HttpPostedFileBase[] fileUpload)
        {
            if (ModelState.IsValid)
            {
                db.Update(homework, DeleteCheckBox, fileUpload);
                db.Save();
                return RedirectToAction("Index");
            }
            return View(homework);
        }

        // GET: Homework/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Homework homework = db.Get(id);
            if (homework == null)
            {
                return HttpNotFound();
            }
            return View(homework);
        }

        // POST: Homework/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Homework homework = db.Get(id);
            db.Delete(homework);
            db.Save();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PhotoSchool2/PhotoSchool2/Views/Homework/Create.cshtml
@model PhotoSchool2.Models.Homework

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Homework", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Homework</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfPhotos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumberOfPhotos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberOfPhotos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, "Attach photos", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("fileUpload", "fileUpload", htmlAttributes: new { type = "file", multiple = "multiple", @class = "input-file" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PhotoSchool2/PhotoSchool2/Views/Homework/Delete.cshtml
@model PhotoSchool2.Models.Homework

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Homework</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfPhotos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfPhotos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>

    <div class="form-group">
        <div class="col-md-10 col-md-offset-2">
            @foreach (var photo in Model.Photos)
            {
                <div class="col">
                    <div class="photo_preview">

                        <a href="@photo.Path" target="_blank">
                            <img src="@Url.Content(photo.Path)" alt="Image">
                        </a>

                    </div>
                </div>
            }
        </div>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PhotoSchool2/PhotoSchool2/Views/Homework/Details.cshtml
@model PhotoSchool2.Models.Homework

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Homework</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfPhotos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfPhotos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>
</div>

<div class="form-group">
    <div class="col-md-10 col-md-offset-2">
        @foreach (var photo in Model.Photos)
        {
            <div class="col">
                <div class="photo_preview">

                    <a href="@photo.Path" target="_blank">
                        <img src="@Url.Content(photo.Path)" alt="Image">
                    </a>

                </div>
            </div>
        }
    </div>
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PhotoSchool2/PhotoSchool2/Views/Homework/Edit.cshtml
@model PhotoSchool2.Models.Homework

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Homework", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Homework</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.Date)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfPhotos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumberOfPhotos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberOfPhotos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Text, new { @class = "form-control textarea", @rows = 7 })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
                @foreach (var photo in Model.Photos)
                {
                    <div class="col">
                        <div class="photo_preview">

                            <a href="@photo.Path" target="_blank">
                                <img src="@Url.Content(photo.Path)" alt="Image">
                            </a>

                        </div>

                        <input id="DeleteCheckBox[@photo.Id]" value="@photo.Id" name="DeleteCheckBox" type="checkbox">
                        <input type="hidden" value="false" name="@photo.Id">
                        <label for="DeleteCheckBox[@photo.Id]">Удалить</label>

                    </div>
                }
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, "Attach photos", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("fileUpload", "fileUpload", htmlAttributes: new { type = "file", multiple = "multiple", @class = "input-file" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PhotoSchool2/PhotoSchool2/Views/Homework/Index.cshtml
@model IEnumerable<PhotoSchool2.Models.Homework>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumberOfPhotos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Text)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberOfPhotos)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Text)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>

        <tr>
            <td colspan="5">
                @foreach (var photo in item.Photos)
                {
                    <div class="col">
                        <div class="photo_preview">

                            <a href="@photo.Path" target="_blank">
                                <img src="@Url.Content(photo.Path)" alt="Image">
                            </a>

                        </div>
                    </div>
                }
            </td>
        </tr>
    }

</table>

PhotoSchool2/PhotoSchool2/Views/Homework/IndexAdmin.cshtml
@model IEnumerable<PhotoSchool2.Models.Homework>

@{
    ViewBag.Title = "IndexAdmin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumberOfPhotos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Text)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberOfPhotos)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Text)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>

        <tr>
            <td colspan="5">
                @foreach (var photo in item.Photos)
                {
                    <div class="col">
                        <div class="photo_preview">

                            <a href="@photo.Path" target="_blank">
                                <img src="@Url.Content(photo.Path)" alt="Image">
                            </a>

                        </div>
                    </div>
                }
            </td>
        </tr>
    }

</table>

PhotoSchool2/PhotoSchool2/Views/Homework/IndexUser.cshtml
@model IEnumerable<PhotoSchool2.Models.Homework>

@{
    ViewBag.Title = "IndexUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumberOfPhotos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Text)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberOfPhotos)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Text)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>

            <td>
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            </td>
        </tr>

        <tr>
            <td colspan="5">
                @foreach (var photo in item.Photos)
                {
                    <div class="col">
                        <div class="photo_preview">

                            <a href="@photo.Path" target="_blank">
                                <img src="@Url.Content(photo.Path)" alt="Image">
                            </a>

                        </div>
                    </div>
                }
            </td>
        </tr>
    }

</table>